theme: jekyll-theme-time-machine
title: Virginia Woolf Diaries
description: The diaries of Virginia Woolf written during the creation of her novel, "To The Lighthouse". These entries were written from 1924 to 1928.
